### author: xin luo, sun chenyu
### create: 2021.3.19, modify: 2026.8.13
### des: 
###    1. Convert the remote sensing image to patches and in reverse.
###    2. Randomly crop multiple-scales patchs from the remote sening image.

import cv2
import random
import numpy as np
import rasterio
from rasterio.warp import reproject, Resampling
from rasterio.transform import from_bounds

class img2patch():
    def __init__(self, img, patch_size, edge_overlay):
        ''' edge_overlay = left overlay or, right overlay
        edge_overlay should be an even number. '''
        if edge_overlay % 2 != 0:
            raise ValueError('Argument edge_overlay should be an even number')
        self.edge_overlay = edge_overlay        
        self.patch_size = patch_size
        self.img = img[:,:,np.newaxis] if len(img.shape) == 2 else img
        self.img_row = img.shape[0]
        self.img_col = img.shape[1]
        self.num_patch_row = np.nan    # valid when call toPatch
        self.num_patch_col = np.nan
        self.start_list = []       #  
        self.img_for_patch = None

    def _get_start_positions(self, image_size):
        '''Generate sliding-window starts and align the last patch to the boundary.'''
        patch_step = self.patch_size-self.edge_overlay
        if image_size <= self.patch_size:
            return [0]
        starts = list(range(0, image_size-self.patch_size+1, patch_step))
        last_start = image_size-self.patch_size
        if starts[-1] != last_start:
            starts.append(last_start)
        return starts

    def toPatch(self):
        '''
        des: 
            convert img to patches. 
        return: 
            patch_list, contains all generated patches.
            start_list, contains all start positions(row, col) of the generated patches. 
        '''
        patch_list = []
        self.start_list.clear()
        row_starts = self._get_start_positions(self.img_row)
        col_starts = self._get_start_positions(self.img_col)
        ## Padding is only needed when an image dimension is smaller than one patch.
        pad_bottom = max(0, self.patch_size-self.img_row)
        pad_right = max(0, self.patch_size-self.img_col)
        self.img_for_patch = np.pad(self.img, ((0, pad_bottom),
                                        (0, pad_right), (0,0)),
                                        mode='constant', constant_values=0)
        self.num_patch_row = len(row_starts)
        self.num_patch_col = len(col_starts)
        for row_start in row_starts:
            for col_start in col_starts:
                patch_list.append(self.img_for_patch[row_start:row_start+self.patch_size,
                                                        col_start:col_start+self.patch_size, :])
                self.start_list.append([row_start, col_start])
        return patch_list

    def higher_patch_crop(self, higher_patch_size):
        '''
        des: 
            crop the higher-scale patch (centered by the given low-scale patch)
                (!!note: the toPatch() should be firstly called when use higher_patch_crop())
        input:
            img, np.array, the original image
            patch_size, int, the lower-scale patch size
            crop_size, int, the higher-scale patch size
            start_list, list, the start position (row,col) corresponding to the original image (generated by the toPatch function)
        return: 
            higher_patch_list, list, contains higher-scale patches corresponding to the lower-scale patches.
        '''
        higher_patch_list = []
        if self.img_for_patch is None:
            raise RuntimeError('The toPatch() should be called before higher_patch_crop()')
        radius_bias = higher_patch_size//2-self.patch_size//2
        img_for_higher_patch = np.pad(self.img_for_patch, ((radius_bias, radius_bias), \
                                            (radius_bias, radius_bias), (0,0)),
                                            mode='constant', constant_values=0)
        for start_i in self.start_list:
            higher_row_start, higher_col_start = start_i
            higher_patch = img_for_higher_patch[higher_row_start:higher_row_start+higher_patch_size, \
                                                            higher_col_start:higher_col_start+higher_patch_size,:]
            higher_patch_list.append(higher_patch)
        return higher_patch_list

    def toImage(self, patch_list):
        '''
        des: 
            merge patches into one image. 
            (!!note: the toPatch() should be firstly called when use toImage())
        '''
        if len(patch_list) != len(self.start_list):
            raise ValueError('The number of patches does not match start_list')
        num_channels = patch_list[0].shape[2]
        output_dtype = np.result_type(patch_list[0].dtype, np.float32)
        img_array = np.zeros((self.img_row, self.img_col, num_channels), dtype=output_dtype)
        weight = np.zeros((self.img_row, self.img_col, 1), dtype=np.float32)
        for patch, start_i in zip(patch_list, self.start_list):
            row_start, col_start = start_i
            row_end = min(row_start+self.patch_size, self.img_row)
            col_end = min(col_start+self.patch_size, self.img_col)
            valid_row = row_end-row_start
            valid_col = col_end-col_start
            img_array[row_start:row_end, col_start:col_end, :] += \
                patch[:valid_row, :valid_col, :]
            weight[row_start:row_end, col_start:col_end, :] += 1
        img_array /= np.maximum(weight, 1)
        return img_array

class crop2patch():
    '''  
    des: crop image to specific-size patch.
    args:
      img: np.array()
      channel_first: True or False.
    '''
    def __init__(self, img, channel_first=False):
      self.channel_first = channel_first
      if self.channel_first: 
        self.img = np.transpose(img, (1,2,0)) 
      else:
        self.img = img

    def toSize(self, size=(256, 256)):
      ''' 
        des: randomly crop corresponding to specific size
        input:
          size: tuble/list, (height, width)
        return: patch, the cropped patch from the image.
      '''
      start_h = random.randint(0, self.img.shape[0]-size[0])
      start_w = random.randint(0, self.img.shape[1]-size[1])
      patch = self.img[start_h:start_h+size[0], 
                       start_w:start_w+size[1],:]
      if self.channel_first:
        patch = np.transpose(patch, (2,0,1))
      return patch

    def toScales(self, scales=(2048, 512, 256), resize = True):
        ''' 
        des: randomly crop multiple-scale patches (from high to low) from remote sensing image.
        input:
            scales: tuple or list (high scale -> low scale)
        return: patches_group_down: list of multiscale patches.
        '''
        height, width = self.img.shape[:-1]
        if height<scales[0] or width<scales[0]:
          raise Exception('The input scale overpass the size of image!')
        patches_group = []
        patch_high = self.toSize(size=(scales[0], scales[0]))
        patches_group.append(patch_high)
        for scale in scales[1:]:
            start_offset = (scales[0]-scale)//2
            patch_lower = patch_high[start_offset:start_offset+scale, 
                                     start_offset:start_offset+scale, :]
            patches_group.append(patch_lower)
        if resize:            
            for i, patch in enumerate(patches_group[:-1]):
                patch_down = cv2.resize(patch, dsize=(scales[-1], scales[-1]), \
                                    interpolation=cv2.INTER_LINEAR)
                patches_group[i] = patch_down            
        if self.channel_first:
          patches_group = [np.transpose(patch_down, (2,0,1)) for patch_down in patches_group]
        return patches_group

